title: Jacob Zietek
email: jzietek@cs.purdue.edu
github_username: jacob-zietek
repository: jacob-zietek/jacob-zietek.github.io


    
theme: minima
  social-links:
    github: https://github.com/jacob-zietek
    linkedin: https://www.linkedin.com/in/jacob-zietek/

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jemoji

defaults:
  - scope:
      type: 'posts'
    values:
      permalink: /:title

exclude:
  - README.md
