title: Jacob Zietek
email: jzietek@cs.purdue.edu
github_username: jacob-zietek
repository: jacob-zietek/jacob-zietek.github.io

theme: minima

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jemoji

defaults:
  - scope:
      type: 'posts'
    values:
      permalink: /:title

exclude:
  - README.md
