theme: jekyll-theme-tactile
title: Jacob Zietek
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
 - Hello!.md
 - index.md
 - README.md
 - how_do_I_start_working_out.md