title: Jacob Zietek
author: jacob-zietek
email: jzietek@cs.purdue.edu
github_username: jacob-zietek
repository: jacob-zietek/jacob-zietek.github.io

description: > # this means to ignore newlines
  CS Undergrad @ Purdue University
  AI Enthusiast

theme: minima

github_username: jacob-zietek
linkedin_username: jacob-zietek
minima:
  social_links:
    github: jacob-zietek
    linkedin: jacob-zietek

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jemoji

defaults:
  - scope:
      type: 'posts'
    values:
      permalink: /:title

exclude:
  - README.md
